deploy:
  script: echo Deploy!
  environment:
    name: xx$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.dev.company.com
    on_stop: stop

stop:
  script: echo Stop!
  when: manual
  environment:
    name: xx$CI_COMMIT_REF_SLUG
    action: stop